# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for thea configurations
Name: jolla-configuration-thea
Requires:
- patterns-sailfish-device-configuration-thea

Summary: Jolla Configuration thea

